### ISSUE TITLE
회원 정보

### ISSUE THREAD

**Issue by NalaJang** [backtothefuture-team/backtothefuture-backend#116]
## 구체적인 요청 사항
**이슈에 대해 설명해 주세요.**
* 이메일 회원가입 시 기입한 사용자들의 정보
* 마이페이지로 불러올 정보
* 마이페이지에서 정보 수정

## 필요한 데이터
**기타 필요한 데이터에 대해 작성해 주세요.**
<회원 등록(회원가입)>
* 약관 동의 중 선택 사항에 체크했는지

<회원 정보 조회>
* 닉네임
* 환불정보(은행명, 예금주, 계좌번호)
* **생년월일, 성별, 거주지 정보는 사용자가 추후에 추가할 수 있습니다.**

<회원 정보 수정>
* 닉네임
* 생년월일
* 성별
* 거주지
* 환불정보(은행명, 예금주, 계좌번호)

## 필요한 논의 사항
* <회원등록>은 이미 있으니까 상세사항은 작성하지 않았습니다.

**Comment by devyuseon** [comment]
# (작성중)
## (고객) 회원 가입 API

- Method: `POST`
- URI: /members/customers
- Request
  -  
- Response
- Authenticated
- Roles

## (고객) 회원 정보 수정 API

- Method: `PATCH`
- URI: /members/customers
- Request
- Response
- Authenticated
- Roles

## (고객) 회원 정보 조회 API

- Method: `GET`
- URI: /members/customers/{memberId}
- Request
- Response
- Authenticated
- Roles

## (고객) 회원 삭제 API

- Method: `DELETE`
- URI: /members/{memberId}
- Request
- Response
- Authenticated
- Roles

**Comment by devyuseon** [comment]
@NalaJang 
회원 관련 기능 일부 완료 했는데, 누락되거나 추가로 필요한거 있는지 확인 하려고 합니다.
요청-응답구조상 프론트에서 구현하기 까다롭거나 한것도 알려주시면 최대한 반영 해보겠습니다
한번 살펴보시고, 피드백 주세요 :)

> https://app.swaggerhub.com/apis/BAGTOTHEFUTUREDEV_1/bagtothefutuer-member/v1.0.0#/
백투더퓨처 지메일로 로그인 하시고 보시면 됩니다. 안보이면 연락주세요!

**추가/수정한 내용**

- 회원가입시 약관 동의기능 추가
- 회원 정보 조회 기능 추가
- 회원 탈퇴 기능 추가
- 회원 정보 업데이트 기능 추가
  - 기본정보 (이름, 휴대전화번호, 생년월일, 계좌정보, 거주지정보) 수정, 추가기능
- 약관 리스트 조회
- 은행 리스트 조회

**Comment by NalaJang** [comment]
앗 😫 !!

<img width="883" alt="image" src="https://github.com/backtothefuture-team/backtothefuture-backend/assets/73895803/1c7e5ff3-8b1d-4f86-a9a5-d70b81f50bf3">

**Comment by devyuseon** [comment]
@NalaJang
앗 ㅎㅎ.. 퍼블릭으로 바꾸려고 했는데 저도 ..
다른 방법 찾아보겠습니다 ㅋㅋ

**Comment by devyuseon** [comment]
@NalaJang 
포스트맨은 제가 지금 편집이 불가능해서

일단 급한대로
https://editor.swagger.io/
여기에
https://raw.githubusercontent.com/backtothefuture-team/backtothefuture-backend/feature/%23116/docs/openapi/member-openapi.yaml
이 내용 복붙해서 봐주시겠어요??

**Comment by NalaJang** [comment]
<img width="450" alt="image" src="https://github.com/backtothefuture-team/backtothefuture-backend/assets/73895803/11823f26-293e-4a85-a853-1265a48281e1">

1. 상단에 이런 에러가 뜨는데 괜찮을까요?

<img width="300" alt="image" src="https://github.com/backtothefuture-team/backtothefuture-backend/assets/73895803/3b2db5cb-a5d0-430e-911b-b24b9fa5e405">
<img width="500" alt="image" src="https://github.com/backtothefuture-team/backtothefuture-backend/assets/73895803/bb0d284f-57bd-4af1-aec7-32d325206d82">

2. 약관 리스트 조회는 설정 화면의 '약관 및 정책'에 사용되는 걸까요?
3. 약관 동의 여부 업데이트도 그 때 사용되는 건지 궁금합니다.

<img width="400" alt="image" src="https://github.com/backtothefuture-team/backtothefuture-backend/assets/73895803/c3637fae-09cc-4303-85ac-32f41a318553">

4. 회원 정보 조회, 탈퇴, 업데이트에서 회원 ID가 필요한데 회원 ID 값은 어디에서 받아오는 지 궁금합니다. 혹시 토큰값일까요?

5. 추후 확장 기능으로 마이 페이지에 프로필 사진 편집도 들어갈 거 같은데 그건 나중에 추가해도 상관 없는 지 궁금합니다.  
일단 저희는 괜찮습니당.

**Comment by devyuseon** [comment]
1. swagger editor 상에서만 보여지는 에러라 일단은 괜찮을 것 같습니다.
2. 약관 리스트 조회는, 프론트상에서 하드코딩 하지 않고 백엔드에서 리스트를 불러와 보여주고, 그때 받은 id를 리스트에 포함해 보내기 위함입니다. 필수 약관이 있어서 회원가입 상에서 정수 리스트를 보내서 필수 약관을 허용하지 않으면 회원가입이 불가능하도록 처리했습니다.
3. 약관 동의 여부 업데이트는 마이페이지 > 약관 및 정책 화면 에서 철회/동의 가능하도록 만든것이 의도입니다
4. 회원 고유 ID인데,, 제가 프론트에서 회원 ID등을 어떻게 보관하는지 몰라서 이부분은 고민이 필요할 것 같습니다.
5. 마이페이지에서 프로필 사진 편집기능은 추후 따로 구현할 예정입니다..!

**Comment by devyuseon** [comment]
@NalaJang 
id문제말고 다른 문제 없으면 머지하구,
저희 대면 회의때나 논의 후 추가 수정 필요하면 그때 해도 될것같습니다 검토 감사드려요☺️

**Comment by NalaJang** [comment]
고생하셨습니다!
