### ISSUE TITLE
이메일 인증 방식 변경

### ISSUE THREAD

**Issue by devyuseon** [backtothefuture-team/backtothefuture-backend#117]
## Description
|As-Is|To-Be|
|---|---|
|인증 메일에 포함된 링크 클릭시 인증완료| 인증 메일에 포함된 '인증코드'를 프론트 화면에 입력

- 프론트에서 인증완료 처리에 어려움이 있어 변경 (@NalaJang 님 요청)
![image](https://github.com/backtothefuture-team/backtothefuture-backend/assets/67352902/0b38e837-d1a7-48f8-8339-94612529ae02)

**Comment by devyuseon** [comment]
아고 자동으로 닫혀버렸네요

**Comment by NalaJang** [comment]
유선님 모두 확인하였습니다. 🙌🏻
그런데 여기에 올려주신 해당 링크에서는 에러가 나더라구요.
노션 개발문서에 올려져있는 링크로 확인했을 때는 괜찮아서 그걸로 진행하였는데, 어떤게 다른건지는 모르겠네요.

**Comment by devyuseon** [comment]
아 깃헙에 띄워진건 단순 보기용 입니닷
cors 설정을 추가로 해줘야 동작하는데 아직은 해놓지 않았어요🙃

**Comment by NalaJang** [comment]
아아. ㅎㅎ 네! 그럼 앞으로도 노션에 올려주신 걸로 확인하도록 하겠습니당.
