### ISSUE TITLE
판매자 상품 관리

### ISSUE THREAD

**Issue by seongolee** [backtothefuture-team/backtothefuture-backend#27]
## Description
- 상품 등록 수정 재고 관리 기능
### 필요한 API 목록
- [ ] 상품 등록 API
- [ ] 상품 삭제 API
- [ ] 상품 재고 수정 API
- [ ] 상품 조회 API

| 구분 | Method | URI | Request | Response | Roles |
| ---- | ---- | ---- | ---- | ---- | ---- |
| **상품 등록 API** | `POST` | /products/{가게번호} | 등록할 상품 정보 전달 |  | `ROLE_ADMIN` `ROLE_STORE_OWNER` |
| **상품 삭제 API** | `DELETE` | /products/{가게번호}/{상품번호} | - |  | `ROLE_ADMIN` `ROLE_STORE_OWNER` |
| **상품 수정 API** | `PATCH` | /products/{가게번호}/{상품번호} | 수정할 항목 전달 |  | `ROLE_ADMIN` `ROLE_STORE_OWNER` |
| **가게 상품 조회 API :: 전체조회** | `GET` | /products/{가게번호} | 가게 상품 모두 조회 |  | `ROLE_ADMIN` `ROLE_STORE_OWNER` `ROLE_USER` |
| **가게 상품 조회 API :: 특정 상품 조회** | `GET` | /products/{가게번호}/{상품번호} | 특정 상품 조회 |  | `ROLE_ADMIN` `ROLE_STORE_OWNER` `ROLE_USER` |

## Etc
- 썸네일 이미지 처리 방법 고민 필요

**Comment by devyuseon** [comment]
키워드를 적어주지 않아도 닫히는군요..; 다시 오픈 했습니다.

**Comment by devyuseon** [comment]
https://github.com/backtothefuture-team/backtothefuture-backend/pull/58
리뷰 바탕으로 uri 다시 고민해봤습니다.

등록 | /store/{storeId}/products
수정 | /store/{storeId}/products/{productId}
삭제 | /store/{storeId}/products/{productId}
조회 | /store/{storeId}/products/{productId} (단건조회)
          /store/{storeId}/products (모든상품조회)

이렇게 진행하려고 합니다. 작업에 참고 부탁드리겠습니다 :)
