### ISSUE TITLE
docker 환경에서 spring -> redis 접근이 안되는 문제

### ISSUE THREAD

**Issue by devyuseon** [backtothefuture-team/backtothefuture-backend#34]
### 문제상황
docker 로 서비스 실행시 다음 에러 발생
```bash
org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:6379
Caused by: java.net.ConnectException: Connection refused
```
- 현재 spring에서 localshot:6379로 redis에 접근
- docker 컨테이너는 컨테이너마다 각각의 ip주소를 가짐
- spring은 `172.26.0.5` redis는 `172.26.0.2`같은 식으로 실행되기 때문에 docker로 올린 spring application에서 localhost로 접근할 시 localhost는 호스트의 ip주소가 아닌 자신 (spring)의 컨테이너를 가리키게 됨
- 따라서 spring에서 redis에 접근시 커넥션 에러 발생

### 해결방법
- 같은 bridge network에 속해있을때 dns name으로 컨테이너간 통신을 함
- 따로 네트워크 설정을 하지 않았기 때문에 default로 bridge 네트워크가 적용되어 spring -> redis로의 접근은 서비스 네임인 `redis`로 접근 가능 할 것으로 보임
- 찾아보니 host.docker.internal 로 도커 -> 호스트 접근할 수 있는 방법이 있긴 하네요.

1. spring의 redis host 설정을 redis의 서비스 네임으로 변경
2. spring 컨테이너 구동시 `host.docker.internal:host-gateway`로 도커 컨테이너에서 호스트로 접근 가능하게 해준 뒤 redis host 설정을 `host.docker.internal`로 변경

## Etc
- 로컬에서 개발시엔 localhost로 접근해야 할텐데, 기본 설정을 localshot로 두고 배포시에 환경변수 설정 등으로 dns 네임으로 덮어쓰게끔 해야하는지? 아니면 프로필을 분리하는게 좋을지? (local/dev) 고민 필요

**Comment by seongolee** [comment]
local/dev 구분없이 컨테이너들을 하나의 네트워크로 묶고, redis 포트 매핑 추가해서 열어주시면 해결 될 것 같습니다.

**Comment by devyuseon** [comment]
@seongolee 
엇 제가 이해를 잘 못했는데,
1. 이미 기본 네트워크 (bridge) 내에 있어 같은 네트워크 내에 있긴 한데, 네트워크를 따로 정의해주는게 좋다는 말씀이신걸까요(이건저도동의)?
2. 'redis 포트 매핑 추가'가 어떤 뜻인지 설명 부탁드리겠습니다..!

**Comment by seongolee** [comment]
@devyuseon
코드를 보지 못하고 이슈 내용만 봐서 너무 간략하게 말씀드렸네요! :(
저희 셋팅을 참고해서 말씀드려볼께요.

**Q. 이미 기본 네트워크 (bridge) 내에 있어 같은 네트워크 내에 있긴 한데, 네트워크를 따로 정의해주는게 좋다는 말씀이신걸까요(이건저도동의)?**
`A. 아닙니다. 예외적인 상황이 존재하긴하지만 현재상황에선 default 네트워크로도 충분하기에 따로 손댈 필요가 없어보입니다.`
**Q. 'redis 포트 매핑 추가'가 어떤 뜻인지 설명 부탁드리겠습니다..!**
`A. localhost 접근을 위해서 ports: - "6379:6379" 이부분을 넣어달라는 뜻이었습니다.`

결과적으로 지금 이 이슈에 대해서는 `bagtothefuture-member: depends-on: - redis` 이부분만 추가해주시면 해결되지 않을까 합니다.

**Comment by devyuseon** [comment]
depends-on 추가해서 테스트는 해보았는데, 컨테이너 시작 순서와는 관련이 없을 듯 해요,,
spring이 올려진 컨테이너에서 localhost는 host가 아닌 자신의 컨테이너를 바라보기 때문에,
localhost:6379로 redis에 접속하려 했을때 connection error가 나는 듯 합니다.
spring에서 redis로의 연결할때의 호스트를 바꿔줘야 할 것 같아요.
compose로 띄울때 환경변수를 전달할 수 있는 방향으로 한 번 수정 해보겠습니다 😷

**Comment by seongolee** [comment]
잘 해결하신 것 같습니다. 👍  redisConfig에 셋팅이 없었군요!! 
bagtothefuture-member: depends-on: - redis 이부분에 대해서 언급한 부분은 시작 순서도 있지만 health checking이 없어서 언급했던 것 이었습니다. docker-compose.yml만 보았을 때 문제 사항이 없어보여서 redis가 안떳는데 실행되지 않았나? 라는 뜻에서 말씀드린 것이었어요

**Comment by devyuseon** [comment]
@seongolee 아하 그렇군요 검토 감사합니다~☺️
